version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    restart: always
    links:
      - db
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test123
      - POSTGRES_USER=admin
      - POSTGRES_DB=membership
  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=test123
    logging:
      driver: none
    volumes:
      - ./pgadmin:/var/lib/pgadmin
volumes:
  postgres:
    external: true
